### ISSUE TITLE
No Java Dumps

### ISSUE THREAD

**Issue by sf-neumann** [sf-janz/sf-debug#27]
When the script doesn´t make any java dumps or memorydumps, but shows that they were maked:
![grafik](https://user-images.githubusercontent.com/53898946/70038526-abe07080-15b8-11ea-953b-6a4720ba4da5.png)

**Comment by ghost** [comment]
It broke during #24:
https://github.com/starface-support/sf-debug/pull/26/commits/48bd51259a716aedd29af2c8ce059b1b38543b80#diff-8e1b0010cec00a29522271e4da9ae2dbR18
